// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/exec-steps/MissionCards.tsx": () => import("../components/mockups/exec-steps/MissionCards.tsx"),
  "./components/mockups/exec-steps/OrbitalRing.tsx": () => import("../components/mockups/exec-steps/OrbitalRing.tsx"),
  "./components/mockups/exec-steps/PulseTrack.tsx": () => import("../components/mockups/exec-steps/PulseTrack.tsx")
};
